apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:RGnYop41aplzYw==,iv:tJPNHoGuQkNYFtgOJgik9VoGQcm3JzbV75Zjv5oeAac=,tag:mW2sjK4NRuT4SRyMh+TcmA==,type:str]
  METALLB_IP_RANGE: ENC[AES256_GCM,data:CMs11S2J9zZGG1Mw0Q9NgfXiBjNcT3194mwy,iv:xDebr6KB5WiCvQtAml9WfGcLGvCOJuDjc/nu+ixs/Mg=,tag:jt4uYfy/LL8rXl3XpaK58w==,type:str]
  TRAEFIK_LOAD_BALANCER_IP: ENC[AES256_GCM,data:0nPl60scKspd/YaXfA==,iv:FvR+F6r2Cuy6lTXW3GV+Bw7e+10xI8T8QOgMs++Iqlc=,tag:scP9cplj9V/YWNVJZcy/2A==,type:str]
sops:
  age:
    - recipient: age1mf0f83wwjpn9q3kym0pupasuy0qdze2zhpwr2c2s8a7al082nd2qg9rhq3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZUZQWlFsYzZDN0tRQXVH
        NUcydXQrRGlhMlBMaE1qeEFreFN1Sm9lM1QwCnJFSU84dHdIM2FsODQ3bVY1ZGpa
        enJqNFpCbVRiMjdaUjJQSGpCQTBzb2MKLS0tIGQxRnVpcUhJckI4dW5ZVFpMMW5Q
        Z0x0b1ZJZzRlNWwrU0kyYjBVWGlaRFkKmSEJrVkRgPaHxQ7CIjgzrHXJJta7Anlr
        8SCq7YEL0C68Ofhr/0/8dBWgtAqa4MVThoMFaZRXNtvnRyPnNM7uNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-07T07:37:44Z"
  mac: ENC[AES256_GCM,data:1aUEM6TjF3OVeOf/XeqYBncSr3lwr4fB7eF7ZXEybSWR9BSmVxGfDKvkyGo9dw6DGFvcRjZI3BoFpHZ+hLomJGPzhlCyOmkQz8l6T7dB4B5gU7QoGh76m3di4wCGqyUPTSiYzAfb20kEbKtL/Js1WNoFt/3Ne64Gro9/QdE1+l8=,iv:VWfVSP4X9sthEIhpqyI5kNllSS0Zz1shu6FY/RWj3Qk=,tag:dLE3kKt9a4CabLQTF4v9Fg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
