apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:9NiBK2BSkoKvcg==,iv:v7HC5QYgcNIbK5vk2TXfAASZjPADBToNejeqpdEd4N8=,tag:RFWRBbtNAqhDbWJ/R4hWJQ==,type:str]
sops:
  age:
    - recipient: age1mf0f83wwjpn9q3kym0pupasuy0qdze2zhpwr2c2s8a7al082nd2qg9rhq3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVVN6RktCVTVYR3FBZW1R
        dmVHZXcxTGdXOXU5UGxGdmdqWXpIaU9UV1Y0CmtacmxBeHNUYzA4RVdTbHB4cXhV
        OEFtdXdwbVZ3eHdDRnp6VFBMYkNqYW8KLS0tIDB5c3I1cmloSGk3NWxsSXZLVmgw
        dWtQbmpKTUdrQmdwNTNJdTlkWmplYlkKK9ZA/zYGwRK7qF36IfHXkF5leueEtCH+
        roIvlcKOaeielYhsfAdOUw8FrF6Hd0kCeQyJHHJHLtylm0ke7RPivg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:19:05Z"
  mac: ENC[AES256_GCM,data:mKVxbD2n9GN0ZKVYSZINqmZgXG+AbvkgUM0PRMA+025NR88l0b6Yi59X1tJmdINvBd+j1XIj5hZ8OFYy7hgMkJIhvLtaaavWk927yiZ4L34DDzh+KWxWneo+zVdVAjtY11NnDeeGv48rolimZwadHPwfLtqtFG+1M24DwCiG9dg=,iv:vASpsBnNL56Krl9kT9vOlEMW9WgOjqRLv1onHTt0uSA=,tag:3ncjgaQZNoNLkyxhKPKyOA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
