apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:SSNkLtvE0U/uVg==,iv:WDGPe8bDBP7VdWNsIxWEJe5OCJJohmXfHgHDHry8hZw=,tag:Zjssy6MEikTZN+cAZg4KXQ==,type:str]
  CILIUM_LB_IP_CIDR: ENC[AES256_GCM,data:d21tXmAmZYIP/ORPX/EH5g==,iv:PfOgj4xHMteWHiAx83zMR2YuL2Nvllv4RV/Oc8LqeQg=,tag:1IunJafrBCdQ0gaDnZEHmg==,type:str]
  TRAEFIK_LOAD_BALANCER_IP: ENC[AES256_GCM,data:aOsdCCLw5DQAdu++pA==,iv:dd/pJGdxtUiog4wVvv56JODCJD57VeiZ8rhcvVV/MRc=,tag:jv6sMa5n78iUgG4Cb8DhmA==,type:str]
sops:
  age:
    - recipient: age1mf0f83wwjpn9q3kym0pupasuy0qdze2zhpwr2c2s8a7al082nd2qg9rhq3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bFlSRU1VcncrRHAyMkQz
        MnNuZmJGUDlza01IekN4dGJQcklTaXNmdVhzCmtzY242MXlQSUQrS3VEVkxsd0lX
        RGVsNGZHeXNSTWtSZE9wd3lDTXpIUGMKLS0tIHYzUktHNFc1dHl1a05Jck8vaVRM
        bHU2OW5ZMzFQdlB0UTdSdkNvSWpmcDgKmFEaIXmLItHofTnoMxCFsaYAieRQftW6
        T64n1wjLY5XtjLjWpW2ILSD592XyhSovv4wvYkxRTAez8oUuSHHiIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-07T18:59:59Z"
  mac: ENC[AES256_GCM,data:wLjJyMB0a2YKM/vYynequ46Rn82k9/H4u+yAYmacHALQlPcn3vDN4hMQCguHVnfGYH8STH9LMOpRtxCEOuJrMuiVFeUBg4n16D73ihyNU/WefizCVYP0S620MOsDQJ8aoZk0okAWo4T/F2bZOMaBAcLExEyic2kQ09B5AX+o4yw=,iv:rM0M+cvuv/WyTVDmRWghNknZanQsqY3xWMrz2Arp3SE=,tag:IMiQbf1B9OaXM3zuU4r9xA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
