apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ITrMzck+bgcoJQ==,iv:2u6aSrVNMjgEA7E+mwYsL8TJ08UjYyFfACVMUG78fmE=,tag:8WzO0Z/iSZVzxQq/ESyp6g==,type:str]
sops:
  age:
    - recipient: age1mf0f83wwjpn9q3kym0pupasuy0qdze2zhpwr2c2s8a7al082nd2qg9rhq3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBES2M0M1FXazNxd3dWeFho
        bk5mblJDSWtOMWZNMzNmUkkrVHJGeGMzNVdBCjZhRUZVbDFhUXZTdXV5b29aVEVv
        OUF5Z25FNE0xNjRtenIzejh2Rk8yRDgKLS0tIFBla2U5MWdGWElUZUtGU2NpWnJ0
        aXVVdlBnbHZpRVdTNkRuZS9DUHdoWGcKb7wXPHgRR16PVWoubk+5cn0m3n6EbzRz
        1LsLF3vlE5z/BCK0lBBiCS3mgt01rXw8YRNjrkcdYn766u4V8GhHoA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-07T19:33:54Z"
  mac: ENC[AES256_GCM,data:idnkfP1WVBfwy2RtccSz1QXIPKmxZ2637gmL0+B+5XMnaiVWUKFkVmiH0DOVeCuQVnhTCFaygR8O2pJoWfbRnlU7BhALpf1aLw61SUVTxJiko6drGtkwku3yMmxJEZIdtK+U3Lx9y9H74BuZCEkw1itXECOAncn0Gp1nSd9Bpvg=,iv:bzd96Epocdl1jV5UujeBJghGK7rYX42R79KZYdLTkOA=,tag:pCY1LSdshxRiEyKKzHZlqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
