apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ITrMzck+bgcoJQ==,iv:2u6aSrVNMjgEA7E+mwYsL8TJ08UjYyFfACVMUG78fmE=,tag:8WzO0Z/iSZVzxQq/ESyp6g==,type:str]
  CILIUM_LB_IP_CIDR: ENC[AES256_GCM,data:ffYsJgl8jvW4v0UG7JstDg==,iv:Bj7c+REymnWDo8d1FakNrHYX62yOeXnl94+FWz2LEIE=,tag:iu9Ay6AayxQnuH0MneC4Iw==,type:str]
  CLUSTER_API_ENDPOINT: ENC[AES256_GCM,data:WZghy5WoLxkTnn2nkKQ=,iv:NXt4wsN5dK1Kl2l3kq26hilc9OhgIjoDN7khPdvaY2s=,tag:e5OOs7YPfet59k9Jvi9bNQ==,type:str]
  POD_CIDR: ENC[AES256_GCM,data:+wNO13yRoo/el0FB,iv:+hmmVrjJAcwyoWI3/9GZF33Y3vaWec2oVMx0g6KZOiE=,tag:Hguav+UaDTt69j3BeMXGSQ==,type:str]
  TRAEFIK_LOAD_BALANCER_IP: ENC[AES256_GCM,data:kv6bMpPhKvsGLkE6dA==,iv:oIi/xfDOBETDYvlc5psQhBJPtA+jpnZ8JtrM8Q4XCVQ=,tag:TgUhAfS5TkNCbYBurkXwYw==,type:str]
sops:
  age:
    - recipient: age1mf0f83wwjpn9q3kym0pupasuy0qdze2zhpwr2c2s8a7al082nd2qg9rhq3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBES2M0M1FXazNxd3dWeFho
        bk5mblJDSWtOMWZNMzNmUkkrVHJGeGMzNVdBCjZhRUZVbDFhUXZTdXV5b29aVEVv
        OUF5Z25FNE0xNjRtenIzejh2Rk8yRDgKLS0tIFBla2U5MWdGWElUZUtGU2NpWnJ0
        aXVVdlBnbHZpRVdTNkRuZS9DUHdoWGcKb7wXPHgRR16PVWoubk+5cn0m3n6EbzRz
        1LsLF3vlE5z/BCK0lBBiCS3mgt01rXw8YRNjrkcdYn766u4V8GhHoA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-07T19:33:54Z"
  mac: ENC[AES256_GCM,data:idnkfP1WVBfwy2RtccSz1QXIPKmxZ2637gmL0+B+5XMnaiVWUKFkVmiH0DOVeCuQVnhTCFaygR8O2pJoWfbRnlU7BhALpf1aLw61SUVTxJiko6drGtkwku3yMmxJEZIdtK+U3Lx9y9H74BuZCEkw1itXECOAncn0Gp1nSd9Bpvg=,iv:bzd96Epocdl1jV5UujeBJghGK7rYX42R79KZYdLTkOA=,tag:pCY1LSdshxRiEyKKzHZlqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
