apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:k2VmGijhM5vEHhCCzpw/ZZ3UlnfZhh8IfNpVeJm/GBjT7MEKZZ3Hrw==,iv:7LvLotznQtL/RGZrwTzsD+dUEXmm4p9RvgsmDC1jyJ0=,tag:L/wJuP0ggNWsJi9+R8qdeQ==,type:str]
sops:
  age:
    - recipient: age1mf0f83wwjpn9q3kym0pupasuy0qdze2zhpwr2c2s8a7al082nd2qg9rhq3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOT2k0dUt0UmUwWjBsaURM
        L0JENER6UEFMemRrNkpsU2ZHekFveHVkekZnCk9ud0YyUXZwdG0wK1llQTV4VzJO
        d2xCR0lTU294dy81N2Nnc2xDc2dWRGMKLS0tIEYySDRIdm5GakNjeUdMd3cvQ2Uw
        bzB2S25HbElpaVBGV3ZWcGZWYlczWjQKJqIZSF0jx6mOujyzgoQzXQslgQakcAnj
        9dGxUDZmYWwbby7F6EriDhkNwi5ARvRftrjH2nYQTvLEwnFEnzHbTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:23:26Z"
  mac: ENC[AES256_GCM,data:kN7dn5c2R4Huj//vLG3+L+ndm9msmYHoQ0o+r61WH2srUplBDF7gOCfcYfavt/9E6DHBlkZGn6R4/XVNARzQu/RyikZnuPA+amaFtJyPwx+e9xDVDdoAlQkmB2lVqFL9IXXZbdL0nfamyQHkv6geZ38x+w0gjXjCjodJbP8E2QU=,iv:s2feAswB+Jw1caGUXZOtHhcdRGmI7vVAI/wHTrGCNGY=,tag:RNmt7RbLIgvJ7loEV8Aszg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
