apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: ingress-nginx
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-wildcard
    kind: ClusterIssuer
  commonName: "*.${externalDomain}"
  dnsNames:
  - "${externalDomain}"
  - "*.${externalDomain}"